### ISSUE TITLE
Infinite loading - timeout 

### ISSUE THREAD

**Issue by ge4r0** [AlfredoRamos/phpbb-ext-seo-metadata#19] opened 2019-08-03 07:15 UTC
I've found a bug that prevent topic from displaying.

Steps to reproduce:
1. Create a topic and put an image from external website that keeps loading forever (returns timeout). E.g [sample](https://img09.tablica.pl/images_tablicapl/dsa3432wes.jpg) 
2. Turn on seo metadata extension
3. Go to the previously created topic

Result: phpbb3 also returns timeout. 😢

There would be nice to have a feature that is trying to check out image dimensions only for like 2 or 3 seconds and give up if it doesn't work.

**Comment by AlfredoRamos** [comment] 2019-08-06 17:55
I need more information:

- What's your phpBB version?
- Which version (of this extension) are you using?
- What's your PHP version?

> Create a topic and put an image from external website that keeps loading forever

Then the image should be fixed however I get the point that you might not be aware of that issue.

> Result: phpbb3 also returns timeout

I can't reproduce the phpBB timeout.

Yes, the image isn't loaded but it doesn't break the board as it shows the posts while trying to get the image in the background, and the extension isn't even trying to get the image at that point.

> There would be nice to have a feature that is trying to check out image dimensions only for like 2 or 3 seconds and give up if it doesn't work.

It sounds easy to do, but it's not, at least not with PHP and in the current state.

When you call a function it will wait for it to finish and only then you can run more code (blocking function calls).

I have no control over the `FastImageSize\FastImageSize::getImageSize()` and my attempts with the PCNTL functions were unsuccessfull, so you might want to open a new issue at [marc1706/fast-image-size](https://github.com/marc1706/fast-image-size) which is the library phpBB (and this extension) uses to get image information.

However as I previously said, I had no fatal problems with `getImageSize()`

**Closed by AlfredoRamos** 2019-08-06 17:55 UTC

**Comment by ge4r0** [comment] 2019-08-07 17:40
Sure, happy to help with that.
 * What's your phpBB version? **3.2.7**
 * Which version (of this extension) are you using? **1.1.0**
 * What's your PHP version? **7.2.18**

> Then the image should be fixed however I get the point that you might not be aware of that
> issue.
What do you mean? Users can add any image that might break in the feature. It's impossible to prevent that.

> I can't reproduce the phpBB timeout.
🤔 
Have you tried to add this image from my first message?
In this case it looks like it's really trying to get the image dimensions while it's impossible because the image's server doesn't return 404 and keeps the connection for a long time.

**Comment by AlfredoRamos** [comment] 2019-08-07 18:16
> What do you mean? Users can add any image that might break in the feature. It's impossible to prevent that.

That's precisely what I meant in my first message...

> Have you tried to add this image from my first message?

Yes, that's exactly what I used on my servers to test and as I said, It showed the topic but not the image (obviously), but It didn't gave me a "phpBB timeout". Check your web server logs (Apache, Nginx, etc).

> In this case it looks like it's really trying to get the image dimensions while it's impossible because the image's server doesn't return 404 and keeps the connection for a long time.

Yes, but as I said, once the method `getImageSize()` is called I can't stop it because PHP waits for it to be finished, that's why I suggested to report the issue upstream.
